language: go

go:
    - 1.6
    - 1.7.x

services:
    - mysql

before_install:
    - wget https://github.com/google/protobuf/releases/download/v3.2.0rc2/protoc-3.2.0rc2-linux-x86_64.zip
    - unzip protoc-3.2.0rc2-linux-x86_64.zip
    - export PATH=$PATH:$(pwd)/bin
    - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
    - cd socketapi/
    - ./build_proto.sh
    - cd ..
    - mysql -e 'CREATE DATABASE dalalstreet_test;'
    - go get github.com/gemnasium/migrate
    - migrate -url mysql://root:@/dalalstreet_test -path ./migrations up

